### PR TITLE
Fix missing static files

### PR DESCRIPTION
**Pull request by iarspider**
Maybe I'm doing it wrong, but if I run `docker-compose up -d` from `spack-monitor` (i.e. from the same directory where `docker-compose.yml` is), the static files are not found by `uwsgi` container.

### CODE REVIEW

**Comment by vsoch** [comment]
Yeah the static files should appear in the root of the install - can you look at your uwsgi logs and see where it says collecting static to?

**Comment by iarspider** [comment]
I guess this line is what you wanted to see:
```
uwsgi    | 172 static files copied to '/code/spackmon/static', 47 unmodified.
```

and nginx complains about missing files:
```
nginx    | 2021/12/08 21:35:19 [error] 22#22: *1 open() "/var/www/static/css/font-awesome.min.css" failed (2: No such file or directory), client: localhost, server: localhost, request: "GET /static/css/font-awesome.min.css HTTP/1.1", host: "localhost", referrer: "http://localhost/"
nginx    | localhost - - [08/Dec/2021:21:35:19 +0000] "GET /static/css/font-awesome.min.css HTTP/1.1" 404 153 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" "-"
nginx    | 2021/12/08 21:35:19 [error] 22#22: *4 open() "/var/www/static/css/nv.d3.css" failed (2: No such file or directory), client: localhost, server: localhost, request: "GET /static/css/nv.d3.css HTTP/1.1", host: "localhost", referrer: "http://localhost/"
nginx    | localhost - - [08/Dec/2021:21:35:19 +0000] "GET /static/css/nv.d3.css HTTP/1.1" 404 153 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" "-"
nginx    | 2021/12/08 21:35:19 [error] 22#22: *3 open() "/var/www/static/css/jquery-ui-1.10.4.css" failed (2: No such file or directory), client: localhost, server: localhost, request: "GET /static/css/jquery-ui-1.10.4.css HTTP/1.1", host: "localhost", referrer: "http://localhost/"
nginx    | localhost - - [08/Dec/2021:21:35:19 +0000] "GET /static/css/jquery-ui-1.10.4.css HTTP/1.1" 404 153 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" "-"
nginx    | 2021/12/08 21:35:19 [error] 23#23: *7 open() "/var/www/static/css/light-bootstrap-dashboard.css" failed (2: No such file or directory), client: localhost, server: localhost, request: "GET /static/css/light-bootstrap-dashboard.css HTTP/1.1", host: "localhost", referrer: "http://localhost/"
```

**Comment by vsoch** [comment]
okay did a little digging - and I think you are spot on! The change was when I adopted the docker-compose to work with K8s - we needed to use a module named whitenoise for the static files, so I updated the path to be relative to the BASE_DIR,  you can see here:

https://github.com/spack/spack-monitor/commit/f7df2d5690c7e24442ddc4424bfde2759aaf9989#diff-214d905e56cb8ab18a9c22f62031ad2c479427d0931b82e88fe58a8506ae4f08

And I did test locally, but I missed the error because my static directory from previous runs still existed. 

So this change is needed - could you also check the docker-compose file in the https directory?

**Comment by iarspider** [comment]
@vsoch done

**Comment by vsoch** [comment]
Perfecto!

Last request - as before, please bump the VERSION to 2.0.2 and add a note for that version to CHANGELOG.md. Release often, that's the name of the game, and yes twice in a day is ok!

Also - the Analysis metrics are very much under development. So if you have feedback / suggestions, please let me know! I would expect a large chunk of them to be removed at some point - they were experimental. Another area that I think needs work is the front page / dashboard - right now it's just a table of builds with failing at top, and I think we can do better. But not a lot of folks have time to engage to talk about UI design so it is what it is.

**Comment by vsoch** [comment]
But actually we can pin the version and I'll do the changelog update for ya. Thanks!

**Pull request merged**
